# Generated by Django 4.0.6 on 2023-04-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nprh', '0002_travelreg_alter_demotable_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='travelreg',
        ),
        migrations.AlterField(
            model_name='demotable',
            name='description',
            field=models.TextField(),
        ),
    ]
